apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-app
  labels:
    app: vuln-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln-app
  template:
    metadata:
      labels:
        app: vuln-app
    spec:
      containers:
      - name: vuln-app
        image: santosomar/vuln-app
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: vuln-app
